BUG - Hint: the following combinations of packages create a conflict with the remaining packages:   - python 2.7*   - cookiecutter
Fatal error: local() encountered an error (return code 1) while executing 'conda
 install -c https://conda.binstar.org/pydanny cookiecutter'